export const state = {
	currentFile: null,
	previewUrl: "",
	thumbUrls: [],
	receiptsCache: [],
	lastOcrText: "",
	installPrompt: null,
	editingReceipt: null,
	dispensaryLookupEntries: null,
	dispensaryLookupPromise: null,
	dispensaryLookupPath: "",
	pendingTrainingAddress: "",
	lastDetectedPhysicalAddress: "",
	lastDispensaryLookupSource: "",
	defaultLocationPlaceholder: "",
};

export const elements = {
	// Main page elements
	settingsToggle: document.getElementById("settingsToggle"),
	receiptInput: document.getElementById("receiptInput"),
	receiptPreview: document.getElementById("receiptPreview"),
	receiptForm: document.getElementById("receiptForm"),
	saveReceiptBtn: document.getElementById("saveReceiptBtn"),
	cancelEditBtn: document.getElementById("cancelEditBtn"),
	scanBtn: document.getElementById("scanBtn"),
	previewWrap: document.getElementById("previewWrap"),
	scanStatus: document.getElementById("scanStatus"),
	locationInput: document.getElementById("locationInput"),
	matchConfidence: document.getElementById("match-confidence"),
	licenseInput: document.getElementById("licenseInput"),
	dateInput: document.getElementById("dateInput"),
	timeInput: document.getElementById("timeInput"),
	amountInput: document.getElementById("amountInput"),
	notesInput: document.getElementById("notesInput"),
	receiptRows: document.getElementById("receiptRows"),
	rowTemplate: document.getElementById("rowTemplate"),
	recordCount: document.getElementById("recordCount"),
	emptyState: document.getElementById("emptyState"),
	runningTotalLabel: document.getElementById("runningTotalLabel"),

	// Settings page elements
	backBtn: document.getElementById("backBtn"),
	exportCsvBtn: document.getElementById("exportCsvBtn"),
	exportZipBtn: document.getElementById("exportZipBtn"),
	importBackupBtn: document.getElementById("importBackupBtn"),
	importBackupInput: document.getElementById("importBackupInput"),
	clearAllReceiptsBtn: document.getElementById("clearAllReceiptsBtn"),
	storageProtectBtn: document.getElementById("storageProtectBtn"),
	chooseBackupFileBtn: document.getElementById("chooseBackupFileBtn"),
	clearBackupFileBtn: document.getElementById("clearBackupFileBtn"),
	installBtn: document.getElementById("installBtn"),
	backupReminderSwitch: document.getElementById("backupReminderSwitch"),
	autoBackupPromptSwitch: document.getElementById("autoBackupPromptSwitch"),
	themeSwitch: document.getElementById("themeSwitch"),
	compactSwitch: document.getElementById("compactSwitch"),
};
